### PR TITLE
improve user search behaviour

### PR DESCRIPTION
**Pull request by Docker-J**
## Description of Changes
Search username that starts with user's input
Able to search multiple user

## Screenshots

https://user-images.githubusercontent.com/2572832/143561484-dd8015cd-f859-4f40-b24d-a9a83c02769a.mp4

## Checklist

- [ ] Automated tests
- [x] Screenshots included (if necessary)
- [x] Code is well commented

Closes #ISSUE_ID

### CODE REVIEW

**Review by AtrazineC — DISMISSED** [review]
looks awesome! Geat job 👍

**Review by MacMalainey — DISMISSED** [review]

**Review by AtrazineC — APPROVED** [review]
Looks awesome! 💯

**Review by loravocado — APPROVED** [review]
Omg this looks so good! Great work!

**Review by cheetiantey — APPROVED** [review]
Good job!

**Pull request merged**
